name: dhoro_mobile
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  flutter_hooks: ^0.17.0
  hooks_riverpod: ^0.14.0+4
  modal_bottom_sheet: ^2.0.0
  flutter_statusbarcolor_ns: ^0.3.0-nullsafety
  shared_preferences: ^2.0.6
  logger: ^1.1.0
  share: ^2.0.4
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  json_annotation: ^4.0.0
  pretty_dio_logger: ^1.1.1
  fluttertoast: ^8.0.8
  get_it:
  moor_flutter:
  android_intent: any
  pull_to_refresh:
  timeago: ^3.1.0
  flutter_cache_manager: ^3.1.2
  permission_handler: ^8.1.4+2
  #page_view_indicators: ^2.0.0
  http: ^0.13.3
  dartz: ^0.9.2
  url_launcher: ^6.0.9
  flutter_vector_icons: ^1.0.0
  cached_network_image: ^3.1.0
  equatable: ^2.0.3
  dio: ^4.0.0
  flutter_svg: 0.22.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.0
  build_runner: ^2.1.1
  logging: ^1.0.0
  json_serializable: ^4.0.3
  flutter_launcher_icons:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
